### ISSUE TITLE
assertion error is coming in BMM_attention_model.py

### ISSUE THREAD

**Issue by kajal15003** [dvatterott/BMM_attentional_CNN#2]

**Comment by dvatterott** [comment]
Hard to say what's going on here without more detail...

I will say this project was a research project that is now done, so I am not actively maintaining this code. 

I suspect the assertion error occurred because you're using updated python libraries. I wish I had recorded the version of all the libraries used here, but live and learn. 

One important change in libraries since this software was built is Keras no longer uses a theano backend by default. This software was written specifically with a theano backend in mind, so please make sure you're using it.
